
services:
  python-server:
    container_name: python-fastapi
    image: boostchavit/backend-python-server:latest
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - backend_network
  db:
      container_name: postgres-db
      image: postgres:15-alpine
      restart: always
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_DB=${POSTGRES_DB}
      env_file:
        - .env
      networks:
        - backend_network
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    networks:
      - backend_network
  
  frontendocr:
    image: siwakorndocker/frontendocr
    container_name: frontendocr
    env_file: .env
    ports:
      - 3000:3000
    environment:
      - BACKEND_URL=${BACKEND_URL}
    networks:
      - backend_network

networks:
  backend_network:
    name: backend_network